REM assumes it starts in directory InstallationTests

REM INCOMPLETE - MOVED TO C# PROJECT

REM Foreach target framework
set installationTestsDirectory=%CD%
set frameworks=20 30 35 40 45 451 452 46 461 462 47 471 472
(for %%f in (%frameworks%) do ( 
	cd %installationTestsDirectory%
	cd AutoGenerated\net%%f
 	REM Foreach oracle file
	for /f %%x in (`dir /b "oracleDocumentation"`) do (
		comp oracleDocumentation\%%x documentation\%%x
	)
))
 
REM Return to starting directory
cd %startingDirectory%